#################1######################
# idade = 19
# if idade >= 18: 
#     print("voce é maior de idade")
# else: print("você é menor de idade")
#################2########################
# password = input("Digite a senha: ")
# if password == "12345":
#     print("Acesso permitido.")
# else:
#     print("Acesso negado, tente novamente")
##################3########################
# numero = input("digite um numero inteiro:")
# if numero %2 == 0:
#     print("o numero é par")
# else: 
#       print("impar")
###############4###########################
nota = int (input("digite sua nota:"))
if nota >= 7:
     print("Aprovado")
else: 
    print("Reprovado")